"""Add status and comment to applications

Revision ID: a64634dba7d0
Revises: db1c1ac0ed94
Create Date: 2026-01-12 16:44:52.981897

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a64634dba7d0'
down_revision: Union[str, Sequence[str], None] = 'db1c1ac0ed94'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Create the Enum type
    application_status = sa.Enum('archive', 'submitted', 'interviewing', 'offered', 'failed', name='applicationstatus')
    application_status.create(op.get_bind())

    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('applications', sa.Column('status', application_status, nullable=False, server_default='submitted'))
    op.add_column('applications', sa.Column('comment', sa.String(), nullable=True))
    op.drop_column('applications', 'created_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('applications', sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('applications', 'comment')
    op.drop_column('applications', 'status')
    # ### end Alembic commands ###

    # Drop the Enum type
    sa.Enum(name='applicationstatus').drop(op.get_bind())
